#!/bin/bash

#Recon script

PATH_TO_DIRSEARCH="/home/safety/tools/dirsearch/"
TODAY=$(date)
	echo "This scan was created on $TODAY"
DOMAIN=$1
DIRECTORY=${DOMAIN}_recon
	echo "Creating directory $DIRECTORY"
mkdir $DIRECTORY

if [ $2 == "nmap-only" ];then

	nmap $DOMAIN > $DIRECTORY/nmap
	echo "The results of namp scan are stored in $DIRECTORY/nmap."
elif [ $2 == "dirsearch-only" ];then

	
	$PATH_TO_DIRSEARCH/dirsearch.py -u $DOMAIN -e php --simple-report=$DIRECTORY/dirsearch
	echo "The results of dirsearch scan are stored in $DIRECTORY/dirsearch."
else
	nmap $DOMAIN > $DIRECTORY/nmap
	echo "The results of nmap scan are stored in $DIRECTORY/nmap."
	$PATH_TO_DIRSEARCH dirsearch.py -u $DOMAIN -e php --simple-report=$DIRECTORY
	echo "The results of dirsearch scan are stored in $DIRECTORY/dirsearch."
fi

