#!/bin/bash

#Recon script

PATH_TO_DIRSEARCH="/home/safety/tools/dirsearch/"
TODAY=$(date)
	echo "This scan was created on $TODAY"
DOMAIN=$1
DIRECTORY=${DOMAIN}_recon
	echo "Creating directory $DIRECTORY"
mkdir $DIRECTORY

#using functions to avoid repetition
nmap_scan(){
    nmap $DOMAIN >$DIRECTORY/nmap
        echo "The results of nmap scan are stored in $DIRECTORY/nmap."
}

dirserach_scan(){
    $PATH_TO_DIRSEARCH/dirsearch.py -u $DOMAIN -e php, js --simple-report --exclude-status 403=$DIRECTORY/dirsearch
    echo "The results of the dirsearch scan is stored in $DIRECTORY/dirsearch."
}

crt_scan(){
    curl "https://crt.sh/?q=$DOMAIN&output==json" -o $DIRECTORY/crt
        echo " The results of crt scan are stored in $DIRECTORY/crt." 
}
#using case statement in place of multiple if/else statements
case $2 in
    nmap_only)
        nmap_scan
        ;;
    dirsearch-only)
        dirserach_scan
        ;;
    crt-only)
        crt_scan
        ;;
    *)
       nmap_scan

       dirserach_scan

        crt_scan
	;;
esac
echo "Generating recon report from output files..."
TODAY=$(date)
echo "This scan was created on $TODAY > $DIRECTORY/report
echo "Results for Nmap:" >> $DIRECTORY/report
grep -E "^\s*\S+\s+\S+\s+\S+\s*$" $DIRECTORY/nmap >> $DIRECTORY/report
echo "Results for Dirsearch:" >> $DIRCTORY/report
cat $DIRECTORY/dirsearch >> $DIRECTORY/report
echo "Results for crt.sh:" >> $DIRECTORY/report
jq -r ".[] | .name_value" >> DIRECTORY/crt >> $DIRECTORY/report





